### PR TITLE
ci: change ESLint options to use "error" and "warn" instead of numbers

### LINKED ISSUE #408: Update ESLint rules
A few of the rules are used with undocumented (possibly deprecated?) parameters:

        "no-trailing-spaces": 2,
        "eol-last": 2,

Since the official ESLint docs to not cover this usage (e.g. [no-trailing-spaces docs](https://eslint.org/docs/rules/no-trailing-spaces)), it would be good to update to something that is documented:

        "no-trailing-spaces": "error",
        "eol-last": "error",

EDIT: I found the docs do cover the meaning of 0, 1, and 2 [here](https://eslint.org/docs/user-guide/configuring/rules#configuring-rules), but I still recommend changing these to the clearer "off", "warn", "error" since that is what is used in most of the examples in the docs.

### PR DESCRIPTION
**Pull request by benjaminpjones**
Fixes #408.

### CODE REVIEW

**Comment by benjaminpjones** [comment]
Anyone monitoring this repo?

**Comment by benjaminpjones** [comment]
Closing after no response for a month.

**Comment by dblythy** [comment]
Reopening as I think this is a good change

**Review by mtrezza — APPROVED** [review]
Yep, makes sense

@dblythy thanks for reopening and apologies to @benjaminpjones for the silence, I didn't receive notifications from this repo  - fixed now.

**Comment by benjaminpjones** [comment]
Oh cool, thanks @dblythy and @mtrezza !

**Pull request merged**
